// https://github.com/oculus-samples/Unity-DepthAPI/issues/16
#include "../DepthKit.hlsl"

#pragma kernel CSMain

RWTexture2D<float4> HeightMap;
RWTexture2D<uint> PerFrameHeightMap;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID) 
{	
    uint normHeightAsUInt = PerFrameHeightMap[id.xy].r;
    PerFrameHeightMap[id.xy].r = 0;
    HeightMap[id.xy] = float4(lerp(HeightMap[id.xy].r, (float) normHeightAsUInt / 255.0, HeightMap[id.xy].g), 0, 0, 0);
} 